import { useState, type ReactNode } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { z } from 'zod';
import { ContactRound, Loader2, Plus, Search, UsersRound } from 'lucide-react';
import { Button } from '../../../components/ui/button';
import { Input } from '../../../components/ui/input';
import { academicApi } from '../../../lib/academic-api';
import { authService } from '../../auth/services/auth.service';

const teacherFormSchema = z.object({ email: z.string().email('Correo no válido'), password: z.string().min(6, 'La clave debe tener al menos 6 caracteres'), ci: z.string().min(1), firstName: z.string().min(1), lastName: z.string().min(1), specialty: z.string().min(1), phone: z.string().optional(), itemNumber: z.string().optional() });
const parentFormSchema = z.object({ email: z.string().email('Correo no válido'), password: z.string().min(6, 'La clave debe tener al menos 6 caracteres'), ci: z.string().min(1), firstName: z.string().min(1), lastName: z.string().min(1), phone: z.string().min(1), address: z.string().optional(), occupation: z.string().optional() });
type TeacherFormData = z.infer<typeof teacherFormSchema>;
type ParentFormData = z.infer<typeof parentFormSchema>;

export function CommunityPage({ mode }: { mode: 'teachers' | 'parents' }) {
  const queryClient = useQueryClient();
  const [search, setSearch] = useState('');
  const canManage = ['ADMIN', 'DIRECTOR', 'SECRETARY'].includes(authService.getCurrentUser()?.role ?? '');
  const canRead = mode === 'teachers' ? ['ADMIN', 'DIRECTOR', 'SECRETARY', 'TEACHER'].includes(authService.getCurrentUser()?.role ?? '') : canManage;
  const teachersQuery = useQuery({ queryKey: ['teachers', search], queryFn: () => academicApi.listTeachers(search), enabled: mode === 'teachers' && canRead });
  const parentsQuery = useQuery({ queryKey: ['parents', search], queryFn: () => academicApi.listParents(search), enabled: mode === 'parents' && canRead });
  const teacherForm = useForm<TeacherFormData>({ resolver: zodResolver(teacherFormSchema), defaultValues: { email: '', password: '', ci: '', firstName: '', lastName: '', specialty: '', phone: '', itemNumber: '' } });
  const parentForm = useForm<ParentFormData>({ resolver: zodResolver(parentFormSchema), defaultValues: { email: '', password: '', ci: '', firstName: '', lastName: '', phone: '', address: '', occupation: '' } });
  const createTeacher = useMutation({ mutationFn: academicApi.createTeacher, onSuccess: () => { teacherForm.reset(); void queryClient.invalidateQueries({ queryKey: ['teachers'] }); } });
  const createParent = useMutation({ mutationFn: academicApi.createParent, onSuccess: () => { parentForm.reset(); void queryClient.invalidateQueries({ queryKey: ['parents'] }); } });
  const title = mode === 'teachers' ? 'Docentes' : 'Familiares';
  const Icon = mode === 'teachers' ? ContactRound : UsersRound;
  const isLoading = mode === 'teachers' ? teachersQuery.isLoading : parentsQuery.isLoading;
  const isError = mode === 'teachers' ? teachersQuery.isError : parentsQuery.isError;

  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-center"><div><h1 className="flex items-center gap-2.5 text-2xl font-bold tracking-tight text-slate-900"><Icon className="h-6 w-6 text-[#F37022]" />{title}</h1><p className="mt-1 text-sm text-slate-600">Administra las cuentas y datos de la comunidad educativa.</p></div></div>
    {canManage && mode === 'teachers' && <form onSubmit={teacherForm.handleSubmit((data) => createTeacher.mutate(data))} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-4"><Field label="Correo asignado" error={teacherForm.formState.errors.email?.message}><Input type="email" {...teacherForm.register('email')} /></Field><Field label="Clave inicial" error={teacherForm.formState.errors.password?.message}><Input type="password" {...teacherForm.register('password')} /></Field><Field label="C.I." error={teacherForm.formState.errors.ci?.message}><Input {...teacherForm.register('ci')} /></Field><Field label="Código de docente"><Input {...teacherForm.register('itemNumber')} /></Field><Field label="Nombres" error={teacherForm.formState.errors.firstName?.message}><Input {...teacherForm.register('firstName')} /></Field><Field label="Apellidos" error={teacherForm.formState.errors.lastName?.message}><Input {...teacherForm.register('lastName')} /></Field><Field label="Especialidad" error={teacherForm.formState.errors.specialty?.message}><Input {...teacherForm.register('specialty')} /></Field><Field label="Celular"><Input {...teacherForm.register('phone')} /></Field><div className="md:col-span-4"><Button type="submit" disabled={createTeacher.isPending} className="bg-[#B91329] text-white"><Plus className="h-4 w-4" />Registrar docente</Button></div></form>}
    {canManage && mode === 'parents' && <form onSubmit={parentForm.handleSubmit((data) => createParent.mutate(data))} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:grid-cols-4"><Field label="Correo asignado" error={parentForm.formState.errors.email?.message}><Input type="email" {...parentForm.register('email')} /></Field><Field label="Clave inicial" error={parentForm.formState.errors.password?.message}><Input type="password" {...parentForm.register('password')} /></Field><Field label="Cédula de identidad" error={parentForm.formState.errors.ci?.message}><Input {...parentForm.register('ci')} /></Field><Field label="Celular" error={parentForm.formState.errors.phone?.message}><Input {...parentForm.register('phone')} /></Field><Field label="Nombres" error={parentForm.formState.errors.firstName?.message}><Input {...parentForm.register('firstName')} /></Field><Field label="Apellidos" error={parentForm.formState.errors.lastName?.message}><Input {...parentForm.register('lastName')} /></Field><Field label="Dirección"><Input {...parentForm.register('address')} /></Field><Field label="Ocupación"><Input {...parentForm.register('occupation')} /></Field><div className="md:col-span-4"><Button type="submit" disabled={createParent.isPending} className="bg-[#B91329] text-white"><Plus className="h-4 w-4" />Registrar familiar</Button></div></form>}
    {!canRead ? <div className="rounded-2xl border border-red-200 bg-red-50 p-8 text-center text-[#B91329]">No tienes permisos para consultar este módulo.</div> : <><div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><Search className="h-4 w-4 text-slate-400" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Buscar ${mode === 'teachers' ? 'docente' : 'familiar'}...`} className="border-0 shadow-none focus-visible:ring-0" /></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{isLoading ? <div className="flex justify-center p-10 text-slate-500"><Loader2 className="mr-2 h-5 w-5 animate-spin" />Cargando {title.toLowerCase()}...</div> : isError ? <p className="p-10 text-center text-[#B91329]">No se pudieron cargar los datos.</p> : mode === 'teachers' ? <TeacherTable data={teachersQuery.data?.data ?? []} /> : <ParentTable data={parentsQuery.data?.data ?? []} />}</div></>}
  </div>;
}

function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium text-slate-700">{label}{children}{error && <span className="text-xs font-normal text-[#B91329]">{error}</span>}</label>; }

function TeacherTable({ data }: { data: Array<{ id: string; firstName: string; lastName: string; itemNumber: string | null; specialty: string; email: string }> }) { return <Table><thead><tr><th className="px-5 py-3">Docente</th><th className="px-5 py-3">Código</th><th className="px-5 py-3">Especialidad</th><th className="px-5 py-3">Correo</th></tr></thead><tbody>{data.map((item) => <tr key={item.id} className="hover:bg-[#fff9e5]"><td className="px-5 py-4 font-semibold">{item.firstName} {item.lastName}</td><td className="px-5 py-4 text-slate-600">{item.itemNumber ?? '—'}</td><td className="px-5 py-4 text-slate-600">{item.specialty}</td><td className="px-5 py-4 text-slate-600">{item.email}</td></tr>)}</tbody></Table>; }
function ParentTable({ data }: { data: Array<{ id: string; firstName: string; lastName: string; ci: string; phone: string; students: Array<{ firstName: string; lastName: string }> }> }) { return <Table><thead><tr><th className="px-5 py-3">Familiar</th><th className="px-5 py-3">C.I.</th><th className="px-5 py-3">Celular</th><th className="px-5 py-3">Estudiantes asociados</th></tr></thead><tbody>{data.map((item) => <tr key={item.id} className="hover:bg-[#fff9e5]"><td className="px-5 py-4 font-semibold">{item.firstName} {item.lastName}</td><td className="px-5 py-4 text-slate-600">{item.ci}</td><td className="px-5 py-4 text-slate-600">{item.phone}</td><td className="px-5 py-4 text-slate-600">{item.students.map((student) => `${student.firstName} ${student.lastName}`).join(', ') || 'Sin asociación'}</td></tr>)}</tbody></Table>; }
function Table({ children }: { children: ReactNode }) { return <div className="overflow-x-auto"><table className="w-full text-left text-sm">{children}</table></div>; }
